title: Paithon Book
author: paithon.it Â© Copyright 2024. Questo lavoro Ã¨ licenziato sotto la
        <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="license noopener noreferrer">
        CC BY-NC-ND 4.0
        </a>
        <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
        src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="cc">
        <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
        src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="by">
        <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
        src="https://mirrors.creativecommons.org/presskit/icons/nc-eu.svg" alt="nc-eu">
        <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
        src="https://mirrors.creativecommons.org/presskit/icons/nd.svg" alt="nd">
logo: figures/logo.png #add your own logo here
copyright: CC BY-NC-ND 4.0

only_build_toc_files: true

execute:
  execute_notebooks: "off"

html:
  favicon : "figures/favicon.ico"
  baseurl :  "https://www.paithon.it/book" #Replace this with your own URL
  home_page_in_navbar       : true
  extra_navbar: |
      <div>
          <script type="text/javascript" src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js" data-name="bmc-button" data-slug="paithon.it" data-color="#BD5FFF" data-emoji="ðŸ•"  data-font="Cookie" data-text="Offrimi una pizza" data-outline-color="#000000" data-font-color="#ffffff" data-coffee-color="#FFDD00" ></script>
      </div>

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      repository_url: "https://github.com/paithon-it/paithonbook" #add your own repo URL here
      use_download_button: false
      use_edit_page_button: false
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
        thebe: true
    html_show_copyright: false
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches

bibtex_bibfiles: 
  - references.bib
